### ISSUE TITLE
gem_mrblib_irep_mruby_arduino undeclared

### ISSUE THREAD

**Issue by teachop** [kyab/mruby-arduino#10]
I have a compile error from a generated file:
gem_init.c:25: error: 'gem_mrblib_irep_mruby_arduino' undeclared (first use in this function).  Can  you point me in the right direction to track it down?

**Comment by kyab** [comment]
Try change `Arduino Due` to `ArduinoDue` in build_config.rb. like

```
MRuby::CrossBuild.new("ArduinoDue") do |conf|
...
```

Seems like current mruby build system can't handle path which include spaces..

If this doesn't help, show me full build_config.rb and build log.

**Comment by kyab** [comment]
I sent pull request for mruby, as https://github.com/mruby/mruby/pull/1405

**Comment by teachop** [comment]
Fine now.  Thank you.
