### ISSUE TITLE
Building for Due

### ISSUE THREAD

**Issue by teachop** [kyab/mruby-arduino#6]
When building for Due with Arduino 1.5.2 to quiet build errors I cast the parameter for analogReference((eAnalogReference)type), and also defined away all tone references.  

The target in mruby include_paths changed to:
["#{SAM_PATH}/system/libsam","#{SAM_PATH}/system/CMSIS/CMSIS/Include/",
"#{SAM_PATH}/system/CMSIS/Device/ATMEL/","#{SAM_PATH}/libraries/",
"#{SAM_PATH}/cores/arduino","#{TARGET_PATH}"]

**Comment by kyab** [comment]
I'll also send pull-request to fix examples/targets/ArduinoDue.rb in mruby.

BTW, have you succeeded to run mruby on your Due?

Thanks you your report!

**Comment by teachop** [comment]
Yes but only hello world stage so far.  Thanks for your work!

**Comment by kyab** [comment]
Nice to hear. I included sample sketch and sample ruby code so please try if you interested.

**Comment by kyab** [comment]
The sample build_config.rb for Due in mruby also fixed. Thanks for report. 
https://github.com/mruby/mruby/commit/c23068e68f0adfb718a504032dfc30d2e7d9dbdb
