### ISSUE TITLE
Arduino Due Blinker

### ISSUE THREAD

**Issue by teachop** [kyab/mruby-arduino#7]
The sample blink sketch built fine with Arduino 1.5.2 and downloaded to the Due.

If Serial.println("blink!") is moved from .rb to the c++ file LED blinking is as expected.

With Serial.println("blink!") in ruby "run" the program gets stuck on the second loop.

Hello Arduino
mruby initialized
Blinker initialized
blink!
(then stuck...)

**Comment by kyab** [comment]
I doubt heap shortage because Due have less RAM(96kb) than chipKitMax32(128kb).

I updated blink.pde to use custom allocator which check memory shortage. Could you try?

If memory shortage is displayed, I recommend to disable all mrbgems except mruby-arduino, or show me your build_config.rb?

**Comment by teachop** [comment]
Thank you.  The blink.pde (it is blink.ino now) is updated.  Rebuilding the library commenting out mruby-hs-regexp allows the blink program to loop as expected.  If mruby-hs-regexp is present, symptoms are as before, "blink!" once and then stuck.  The allocator debugging message does not print out unfortunately.

MRuby::CrossBuild.new("Arduino Due") do |conf|
  toolchain :gcc

  conf.gem 'examples/mrbgems/c_extension_example'

  # GNU Linux
  ARDUINO_PATH = '/home/teachop/arduino-1.5.2'
  BIN_PATH = "#{ARDUINO_PATH}/hardware/tools/g++_arm_none_eabi/bin"
  SAM_PATH = "#{ARDUINO_PATH}/hardware/arduino/sam"
  TARGET_PATH = "#{SAM_PATH}/variants/arduino_due_x"

  conf.cc do |cc|
    cc.command = "#{BIN_PATH}/arm-none-eabi-gcc"
    cc.include_paths << ["#{SAM_PATH}/system/libsam","#{SAM_PATH}/system/CMSIS/CMSIS/Include/",
                        "#{SAM_PATH}/system/CMSIS/Device/ATMEL/","#{SAM_PATH}/libraries",
                        "#{SAM_PATH}/cores/arduino","#{TARGET_PATH}"]
    cc.flags = %w(-g -Os -w -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 
                -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=152 -D__SAM3X8E__ -mthumb -DUSB_PID=0x003e -DUSB_VID=0x2341 -DUSBCON)
    cc.compile_options = "%{flags} -o %{outfile} -c %{infile}"

```
#configuration for low memory environment
cc.defines << %w(MRB_HEAP_PAGE_SIZE=64)
cc.defines << %w(MRB_USE_IV_SEGLIST)
cc.defines << %w(KHASH_DEFAULT_SIZE=8)
cc.defines << %w(MRB_STR_BUF_MIN_SIZE=20)
cc.defines << %w(MRB_GC_STRESS)
#cc.defines << %w(DISABLE_STDIO) #if you dont need stdio.
#cc.defines << %w(POOL_PAGE_SIZE=1000) #effective only for use with mruby-eval
```

  end

  conf.cxx do |cxx|
    cxx.command = conf.cc.command.dup
    cxx.include_paths = conf.cc.include_paths.dup
    cxx.flags = conf.cc.flags.dup
    cxx.defines = conf.cc.defines.dup
    cxx.compile_options = conf.cc.compile_options.dup
  end

  conf.archiver do |archiver|
    archiver.command = "#{BIN_PATH}/arm-none-eabi-ar"
    archiver.archive_options = 'rcs %{outfile} %{objs}'
  end

  #no executables
  conf.bins = []

  #do not build executable test
  conf.build_mrbtest_lib_only

  #gems from core
  conf.gem :core => "mruby-print" 
  conf.gem :core => "mruby-math"
  conf.gem :core => "mruby-enum-ext"

  #light-weight regular expression
  conf.gem :github => "masamitsu-murase/mruby-hs-regexp", :branch => "master" 

  #Arduino API
  conf.gem :github =>"kyab/mruby-arduino", :branch => "master"

**Comment by kyab** [comment]
Nice to hear blink to work.Thanks for your try.

Working with Due seems to be hard. hope this sketch helps...

```
#include <Servo.h>

#ifdef MPIDE
#else
#include <Arduino.h>
#endif

#include <stdio.h>

#include "mruby.h"
#include "mruby/class.h"
#include "mruby/value.h"
#include "mruby/irep.h"

//change heap size
#ifdef MPIDE
#define CHANGE_HEAP_SIZE(size) __asm__ volatile ("\t.globl _min_heap_size\n\t.equ _min_heap_size, " #size "\n")
CHANGE_HEAP_SIZE(110 * 1024);
#endif

mrb_state *mrb;
mrb_value blinker_obj;
int ai;

extern const uint8_t blinker[];

void printlnSize(size_t size){
    char str[15];
    sprintf(str,"%u", size);
    Serial.println(str);
}
// custom allocator to check heap shortage.
void *myallocf(mrb_state *mrb, void *p, size_t size, void *ud){
    if (size == 0){
        free(p);
        return NULL;
    }

    void *ret = realloc(p, size);
    if (!ret){
        Serial.print("memory allocation error. size:");
        printlnSize(size);
    }
}

void setup(){

    Serial.begin(9600);
    Serial.println("Hello Arduino");

    //Init mruby
    mrb = mrb_open_allocf(myallocf, NULL);

    //Load Blinker bytecode
    mrb_load_irep(mrb, blinker);

    Serial.println("mruby initialized");

    //Get Blinker class and create instance.
    //equivalent to ruby: blinker_obj = Blinker.new(13,1000)
    RClass *blinker_class = mrb_class_get(mrb, "Blinker");
    if (mrb->exc){
        Serial.println("failed to load class Blinker");
    }

    mrb_value args[2];
    args[0] = mrb_fixnum_value(13);     //pin Number
    args[1] = mrb_fixnum_value(1000);   //interval
    blinker_obj = mrb_class_new_instance(mrb, 2, args, blinker_class);

    //is exception occure?
    if (mrb->exc){
        Serial.println("failed to create Blinker instance");
        return;
    }

    ai = mrb_gc_arena_save(mrb);

}

void loop(){

    mrb_funcall(mrb, blinker_obj, "run", 0);

    //is exception occure?
    if (mrb->exc){
        Serial.println("failed to run!");
        mrb->exc = 0;
        delay(1000);
    }

    mrb_gc_arena_restore(mrb,ai);
}



//required to link with mruby-arduino
void __dummy(){
  random(1,1);
#ifdef MPIDE
  tone(1,2,3);
#endif
  pulseIn(1,2,3);
  shiftOut(1,2,3,4);
}
```

**Comment by teachop** [comment]
The results are unchanged.  I suppose the Due just doesn't have enough memory to do much with mruby.
